M48
; DRILL file {KiCad 6.0.0-d3dd2cf0fa~116~ubuntu20.04.1} date Thu 30 Dec 2021 07:41:59 AM EST
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2021-12-30T07:41:59-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.0-d3dd2cf0fa~116~ubuntu20.04.1
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C1.000
%
G90
G05
T1
X54.356Y-25.4
T0
M30
