M48
; DRILL file {KiCad 6.0.6-3a73a75311~116~ubuntu22.04.1} date Sat 16 Jul 2022 02:16:35 PM EDT
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-07-16T14:16:35-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.6-3a73a75311~116~ubuntu22.04.1
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C1.000
%
G90
G05
T1
X103.886Y-96.52
T0
M30
